# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    cache: "media_custom_resolver"
    resolvers:
        media_custom_resolver:
            web_path:
                cache_prefix: media_custom/cache
                
    filter_sets:
        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size: [500, 500]
                    mode: outbound
                    allow_upscale: true
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true
        squared_thumbnail_mini:
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound
                    allow_upscale: true
